name: Deploy to Cloudflare Workers via Docker

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and deploy using Docker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Build the Docker image
          echo "Building Docker image..."
          docker build -t cloudflare-d1-api .
          
          # Run the container to deploy to Cloudflare
          # The container will handle both migrations and deployment
          echo "Deploying to Cloudflare Workers..."
          docker run --rm \
            -e CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
            -e CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
            cloudflare-d1-api
      
      - name: Verify deployment
        run: |
          echo "✅ Deployment to Cloudflare Workers completed successfully!"
          echo "🌐 Your API should now be available at your configured route or at the Workers subdomain."
